export type ManagedRuntimeEnv = Env & {
  MANAGED_RUNTIME_ORIGIN: string
  MANAGED_RUNTIME_SERVICE_SECRET: string
  AUTH_STATE_SERVICE_SECRET: string
  MANAGED_RUNTIME_GRANT_SECRET: string
  MANAGED_CONTROL_PLANE_URL: string
  MANAGED_RUNTIME_MAX_EGRESS_BYTES: string
  MANAGED_RUNTIME_MAX_CHECKPOINT_BYTES: string
  MANAGED_RUNTIME_CHECKPOINT_RETENTION_SECONDS: string
}
