import { mkdirSync, realpathSync, writeFileSync } from "node:fs"
import { mkdir, realpath, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { expect, test } from "./fixtures.js"

test("Obsidian previews a configured local vault and refreshes external edits", async ({ launchApp }) => {
  const { window, home } = await launchApp({ configured: true, withRepo: true, seed: ({ home }) => {
    const vault = join(home, "vault")
    mkdirSync(vault)
    writeFileSync(join(vault, "known.md"), "# Known vault note")
    for (let index = 0; index < 12; index++) writeFileSync(join(vault, `note-${index}.md`), `# Note ${index}`)
    const alternatives = Object.fromEntries(Array.from({ length: 8 }, (_, index) => {
      const path = join(home, `vault-alt-${index}`)
      mkdirSync(path)
      return [`alternative-${index}`, { path: realpathSync(path) }]
    }))
    const metadata = process.platform === "darwin" ? join(home, "Library", "Application Support", "obsidian")
      : process.platform === "win32" ? join(home, "AppData", "Roaming", "obsidian") : join(home, ".config", "obsidian")
    mkdirSync(metadata, { recursive: true })
    writeFileSync(join(metadata, "obsidian.json"), JSON.stringify({ vaults: { opaque: { path: realpathSync(vault), ts: 123, open: true }, ...alternatives } }))
  }, e2eEnv: { XDG_CONFIG_HOME: "", APPDATA: "" }, sessions: [{
    id: "obsidian-preview", repo: "widget", branch: "notes", title: "Vault preview", status: "idle",
    diff: { added: 0, removed: 0 }, prNumber: null, costUsd: 0, tokens: 0, updatedAt: "2026-10-07T00:00:00.000Z"
  }] })
  const vaultPath = join(home, "vault")
  await mkdir(vaultPath, { recursive: true })
  const vault = await realpath(vaultPath)
  await writeFile(join(vault, "one.md"), "# First note\n\n**Rendered Markdown**")
  await writeFile(join(vault, "two.md"), "# Second note")
  await writeFile(join(vault, "ignored.txt"), "not a note")
  await window.getByTestId("session-row-obsidian-preview").click()
  await window.getByRole("button", { name: "Obsidian", exact: true }).click()
  await expect(window.getByTestId("obsidian-vault-choices")).toHaveCSS("max-height", "192px")
  await expect(window.getByLabel("Vault path")).toHaveValue("")
  await window.getByRole("button", { name: `vault ${vault}`, exact: true }).click()
  await expect(window.getByLabel("Vault path")).toHaveValue(vault)
  await expect(window.getByTestId("obsidian-preview")).not.toContainText("Known vault note")
  await window.getByRole("button", { name: "Save vault" }).click()
  await expect(window.getByTestId("obsidian-preview").getByRole("heading", { name: "Known vault note" })).toBeVisible()
  await window.setViewportSize({ width: 900, height: 600 })
  const divider = await window.getByRole("separator", { name: "Resize editor group 1" }).boundingBox()
  if (!divider) throw new Error("Missing editor split divider")
  await window.mouse.move(divider.x + divider.width / 2, divider.y + divider.height / 2)
  await window.mouse.down()
  await window.mouse.move(divider.x + divider.width / 2 + 160, divider.y + divider.height / 2, { steps: 8 })
  await window.mouse.up()
  await expect.poll(() => window.getByTestId("obsidian-notes").evaluate((el) => el.getBoundingClientRect().width)).toBeLessThan(400)
  await expect(window.getByTestId("obsidian-browser-layout")).toHaveClass(/flex-col/)
  const choices = window.getByTestId("obsidian-vault-choices")
  expect(await choices.evaluate((el) => el.scrollHeight > el.clientHeight)).toBe(true)
  const noteList = window.getByRole("navigation", { name: "Vault notes" })
  expect(await noteList.evaluate((el) => el.scrollHeight > el.clientHeight)).toBe(true)
  const stackedPreview = window.getByTestId("obsidian-preview")
  expect(await stackedPreview.locator("..").evaluate((el) => el.getBoundingClientRect().height)).toBeGreaterThanOrEqual(256)
  expect(await stackedPreview.evaluate((el) => el.getBoundingClientRect().height)).toBeGreaterThan(200)
  await stackedPreview.scrollIntoViewIfNeeded()
  await expect(stackedPreview.getByRole("heading", { name: "Known vault note" })).toBeVisible()
  await window.setViewportSize({ width: 1500, height: 900 })
  await window.reload()
  await window.getByTestId("session-row-obsidian-preview").click()
  await window.getByRole("button", { name: "Obsidian", exact: true }).click()
  await expect(window.getByLabel("Vault path")).toHaveValue(vault)
  await window.getByLabel("Vault path").fill("relative")
  await window.getByRole("button", { name: "Save vault" }).click()
  await expect(window.getByRole("alert")).toContainText("absolute")
  await window.getByLabel("Vault path").fill(vault)
  await window.getByRole("button", { name: "Save vault" }).click()
  await window.getByRole("button", { name: "one.md", exact: true }).click()
  const preview = window.getByTestId("obsidian-preview")
  await expect(preview.getByRole("heading", { name: "First note" })).toBeVisible()
  await expect(preview.getByText("Rendered Markdown")).toBeVisible()
  await expect(preview).not.toContainText("**Rendered Markdown**")
  await expect(window.getByRole("navigation", { name: "Vault notes" })).not.toContainText("ignored.txt")
  await expect(preview.locator("textarea, input, [contenteditable=true]")).toHaveCount(0)
  await window.getByRole("button", { name: "two.md", exact: true }).click()
  await expect(preview.getByRole("heading", { name: "Second note" })).toBeVisible()
  await writeFile(join(vault, "two.md"), "# Updated externally")
  await window.getByRole("button", { name: "Refresh notes" }).click()
  await expect(preview.getByRole("heading", { name: "Updated externally" })).toBeVisible()
  await window.reload()
  await window.getByTestId("session-row-obsidian-preview").click()
  await window.getByRole("button", { name: "Obsidian", exact: true }).click()
  await expect(window.getByLabel("Vault path")).toHaveValue(vault)
  await expect(preview.getByRole("heading", { name: "Known vault note" })).toBeVisible()
})
