import { createHash } from "node:crypto"
import { existsSync, readFileSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { addProject, appShell, expect, test } from "./fixtures.js"

test("saves a routine through Settings and runs the real checkpoint-gated Pi into a linked fresh worktree", async ({ launchApp }) => {
  const launched = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  const { window, repoPath, home } = launched
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Settings" }).click()
  await window.getByRole("button", { name: "Routines", exact: true }).click()
  const routines = window.getByRole("region", { name: "Saved desktop routines" })
  await routines.getByLabel("Name", { exact: true }).fill("Routine proof")
  await routines.getByLabel("Prompt", { exact: true }).fill("READONLY routine proof: inspect README.md")
  await routines.getByLabel(/I approve these exact settings/).check()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  const document = () => JSON.parse(readFileSync(join(home, "jingler/routines.json"), "utf8"))
  await expect.poll(() => document().runs[0]?.status).toBe("running")
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  await expect.poll(() => document().runs.filter((run: { status: string }) => run.status === "skipped").length).toBe(1)
  await expect.poll(() => document().runs[0]?.status, { timeout: 30000 }).toBe("succeeded")
  const run = document().runs[0]
  const sessions = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  const session = sessions.find((item: { id: string }) => item.id === run.requestedSessionId)
  expect(run.sessionId).toBe(session.id)
  expect(session.routineOccurrence).toEqual({ routineId: run.routineId, runId: run.id })
  expect(session.modelId).toBe(document().routines[0].modelId)
  expect(session.connectionId).toBe(document().routines[0].connectionId)
  expect(session.endpointId).toBe(document().routines[0].endpointId)
  expect(session.checkpointSafeMode).toBe(true); expect(session.checkpointExecutionHistory).toBe("clean")
  expect(session.workspaceLifecycle.status).toBe("setup-skipped")
  expect(session.worktreePath).not.toBe(repoPath)
  expect(readFileSync(join(session.worktreePath, "README.md"), "utf8")).toBe("# e2e repo\n")
  expect(session.chats.find((chat: { id: string }) => chat.id === session.activeChatId).mode).toBe("ask")
  expect(readFileSync(join(repoPath, "README.md"), "utf8")).toBe("# e2e repo\n")
  expect(existsSync(join(repoPath, "routine-proof.txt"))).toBe(false)
  const checkpointRoot = join(home, "jingler/checkpoints", createHash("sha256").update(session.id).digest("hex"))
  const snapshots = readdirSync(checkpointRoot).filter(id => !id.endsWith(".tmp")).map(id => JSON.parse(readFileSync(join(checkpointRoot, id, "snapshot.json"), "utf8")))
  expect(snapshots.some(item => item.summary.label.startsWith("Before agent turn"))).toBe(true)
  const transcript = () => readFileSync(join(home, "jingler/transcripts", `${encodeURIComponent(session.activeChatId)}.json`), "utf8")
  await expect.poll(transcript).toContain("workspace_read_file")
  expect(transcript()).toContain("# e2e repo")
  await expect(routines.getByRole("button", { name: "Open workspace Routine proof" })).toBeVisible()
  await routines.getByRole("button", { name: "Edit Routine proof", exact: true }).click()
  await routines.getByRole("combobox", { name: "Schedule", exact: true }).selectOption("interval")
  const next = new Date(Date.now() + 5000)
  const local = new Date(next.getTime() - next.getTimezoneOffset() * 60000).toISOString().slice(0, 19)
  await routines.getByLabel("First occurrence").fill(local)
  await routines.getByLabel("Interval minutes").fill("1")
  await routines.getByLabel("Enable schedule").check()
  await routines.getByLabel(/I approve these exact settings/).check()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await expect.poll(() => document().runs.filter((item: { trigger: string; status: string }) => item.trigger === "scheduled" && item.status === "succeeded").length, { timeout: 30000 }).toBe(1)
  await routines.getByRole("button", { name: "Disable Routine proof", exact: true }).click()
  await expect.poll(() => document().routines[0].enabled).toBe(false)
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  await expect(routines.getByRole("button", { name: "Cancel Routine proof", exact: true })).toBeVisible()
  await routines.getByRole("button", { name: "Cancel Routine proof", exact: true }).click()
  await expect.poll(() => document().runs.filter((item: { status: string }) => item.status === "cancelled").length).toBe(1)

  await routines.getByRole("button", { name: "Open workspace Routine proof" }).first().click()
  await expect(window.getByTestId("workspace-checkpoints")).toBeVisible()
  const ids = document().runs.map((item: { id: string }) => item.id)
  await launched.app.close()
  const reopened = await launchApp({ home, reposDir: launched.reposDir, userDataDir: launched.userDataDir, configured: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  await expect(appShell(reopened.window)).toBeVisible()
  await reopened.window.getByRole("button", { name: "Account menu" }).click()
  await reopened.window.getByRole("menuitem", { name: "Settings" }).click()
  await reopened.window.getByRole("button", { name: "Routines", exact: true }).click()
  await expect(reopened.window.getByRole("button", { name: "Run now Routine proof", exact: true })).toBeVisible()
  expect(document().runs.map((item: { id: string }) => item.id)).toEqual(ids)

})

test("Ask WRITE routine needs attention without approval or mutation", async ({ launchApp }) => {
  const { window, repoPath, home } = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Settings" }).click()
  await window.getByRole("button", { name: "Routines", exact: true }).click()
  const routines = window.getByRole("region", { name: "Saved desktop routines" })
  await routines.getByLabel("Name", { exact: true }).fill("Ask write proof")
  await routines.getByLabel("Prompt", { exact: true }).fill("WRITE routine proof: write routine-proof.txt")
  await routines.getByLabel(/I approve these exact settings/).check()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await routines.getByRole("button", { name: "Run now Ask write proof", exact: true }).click()
  const document = () => JSON.parse(readFileSync(join(home, "jingler/routines.json"), "utf8"))
  await expect.poll(() => document().runs[0]?.status, { timeout: 30000 }).toBe("needs-attention")
  const run = document().runs[0]
  const sessions = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  const session = sessions.find((item: { id: string }) => item.id === run.requestedSessionId)
  expect(session.chats.find((chat: { id: string }) => chat.id === session.activeChatId).mode).toBe("ask")
  expect(session.modelId).toBe(document().routines[0].modelId)
  expect(session.connectionId).toBe(document().routines[0].connectionId)
  expect(session.endpointId).toBe(document().routines[0].endpointId)
  expect(session.checkpointSafeMode).toBe(true)
  expect(existsSync(join(session.worktreePath, "routine-proof.txt"))).toBe(false)
  expect(existsSync(join(repoPath, "routine-proof.txt"))).toBe(false)
  expect(readFileSync(join(repoPath, "README.md"), "utf8")).toBe("# e2e repo\n")
})
