import { execFileSync } from "node:child_process"
import { readFileSync, writeFileSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { addProject, appShell, expect, test } from "./fixtures.js"

test("safe creation captures before the production Pi turn and restores files and staging while preserving secrets", async ({ launchApp }) => {
  const { window, repoPath, home } = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-checkpoints", authRoute: "api-key" } })
  const git = (cwd: string, ...args: string[]) => execFileSync("git", args, { cwd, encoding: "utf8", stdio: "pipe" }).trim()
  writeFileSync(join(repoPath, "checkpoint-proof.txt"), "base")
  writeFileSync(join(repoPath, ".gitignore"), "secret\n")
  git(repoPath, "add", "."); git(repoPath, "commit", "-qm", "checkpoint fixture")
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByTestId("new-session").click()
  await expect(window.getByText(/File rename is unsupported in safe mode; no files are changed/)).toBeVisible()
  await window.getByLabel("Checkpoint-safe mode", { exact: true }).check()
  await window.getByRole("button", { name: "Create workspace" }).click()
  await expect(window.getByRole("button", { name: "More conversation actions" })).toBeVisible({ timeout: 20000 })
  const sessions = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  const session = sessions[0] as { worktreePath: string; checkpointSafeMode: boolean; checkpointExecutionHistory: string }
  expect(session.checkpointSafeMode).toBe(true); expect(session.checkpointExecutionHistory).toBe("clean")
  const cwd = session.worktreePath
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "staged"); git(cwd, "add", "checkpoint-proof.txt")
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "unstaged")
  writeFileSync(join(cwd, "secret"), "never captured")
  const composer = window.getByPlaceholder("Message the agent…")
  writeFileSync(join(cwd, "intent"), "untracked"); git(cwd, "add", "-N", "intent")
  await composer.fill("Edit the checkpoint proof"); await composer.press("Enter")
  await expect(window.getByText(/Checkpoint capture failed; the turn was blocked/)).toBeVisible({ timeout: 20000 })
  expect(readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("unstaged")
  await expect(window.getByText("Checkpoint edit complete.", { exact: true })).toHaveCount(0)
  git(cwd, "reset", "--", "intent")
  await composer.fill("Retry the checkpoint edit"); await composer.press("Enter")
  await expect.poll(() => readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("changed")
  const overflow = window.getByRole("button", { name: "More conversation actions" })
  await expect(window.getByRole("button", { name: "Checkpoints", exact: true })).toHaveCount(0)
  await overflow.focus()
  await window.keyboard.press("ArrowDown")
  await expect(window.getByRole("menuitem", { name: "Checkpoints", exact: true })).toBeFocused()
  await window.keyboard.press("Enter")
  const activeDialog = window.getByRole("dialog", { name: "Workspace checkpoints" })
  await expect.poll(() => activeDialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
  await activeDialog.getByText(/Before agent turn/).locator("..").getByRole("button", { name: "Preview restore" }).click()
  await expect(activeDialog.getByRole("alert")).toContainText("Stop all workspace work")
  await expect(window.getByText("Checkpoint edit complete.", { exact: true })).toHaveCount(0)
  await activeDialog.getByRole("button", { name: "Cancel" }).click()
  await activeDialog.getByRole("button", { name: "Cancel" }).click()
  await expect(overflow).toBeFocused()
  await expect(window.getByText("Checkpoint edit complete.", { exact: true })).toBeVisible({ timeout: 20000 })
  expect(readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("changed")
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staged")
  // Change the index too: restoring only worktree bytes must not pass this test.
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "staged after capture")
  git(cwd, "add", "checkpoint-proof.txt")
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "changed")
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staged after capture")
  const root = join(home, "jingler/checkpoints")
  const snapshots = readdirSync(root).flatMap((owner) => readdirSync(join(root, owner)).filter((id) => !id.endsWith(".tmp")).map((id) => JSON.parse(readFileSync(join(root, owner, id, "snapshot.json"), "utf8"))))
  expect(snapshots.some((item) => item.summary.label.startsWith("Before agent turn"))).toBe(true)
  expect(snapshots.every((item) => !item.files.some((file: { path: string }) => file.path === "secret"))).toBe(true)
  await window.getByRole("button", { name: "More conversation actions" }).click()
  await window.getByRole("menuitem", { name: "Checkpoints", exact: true }).click()
  const dialog = window.getByRole("dialog", { name: "Workspace checkpoints" })
  await dialog.getByText(/Before agent turn/).locator("..").getByRole("button", { name: "Preview restore" }).click()
  // Assistant text can arrive before the harness's finalizers release admission.
  await expect.poll(async () => {
    const settling = dialog.getByRole("alert").filter({ hasText: "Stop all workspace work" })
    if (await settling.isVisible()) await dialog.getByRole("button", { name: "Retry", exact: true }).click()
    return dialog.getByRole("list", { name: "Workspace file changes" }).getByText("overwrite: checkpoint-proof.txt", { exact: true }).isVisible()
  }).toBe(true)
  await expect(dialog).toContainText("Stop external editors and file watchers before confirming")
  await expect(dialog).toContainText("cannot lock external writers")
  await dialog.getByRole("button", { name: "Confirm restore" }).click()
  await expect(dialog.getByText(/pinned recovery backup/)).toBeVisible()
  expect(readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("unstaged")
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staged")
  expect(readFileSync(join(cwd, "secret"), "utf8")).toBe("never captured")
  // Isolate an index-only change and assert its visible preview before confirming.
  await dialog.getByRole("button", { name: "Capture checkpoint", exact: true }).click()
  await expect(dialog.getByText(/^Manual checkpoint ·/)).toBeVisible()
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "staging-only preview proof")
  git(cwd, "add", "checkpoint-proof.txt")
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "unstaged")
  await dialog.getByText(/^Manual checkpoint ·/).locator("..").getByRole("button", { name: "Preview restore" }).click()
  await expect(dialog.getByText("Workspace file changes", { exact: true }).locator("+ ul").getByRole("listitem")).toHaveCount(0)
  await expect(dialog.getByText("Staging changes", { exact: true }).locator("+ ul")).toContainText("overwrite: checkpoint-proof.txt")
  await expect(dialog.getByText("Staging changes", { exact: true }).locator("+ ul + pre")).toContainText("staging-only preview proof")
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staging-only preview proof")
  await dialog.getByRole("button", { name: "Confirm restore" }).click()
  await expect(dialog.getByText(/pinned recovery backup/)).toBeVisible()
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staged")
  // The latest successful restore retains a usable pinned recovery backup.
  await dialog.getByText(/· pinned recovery backup$/).locator("..").getByRole("button", { name: "Preview restore" }).click()
  await expect(dialog.getByRole("list", { name: "Workspace file changes" }).getByRole("listitem")).toHaveCount(0)
  await expect(dialog.getByText("Staging changes", { exact: true }).locator("+ ul")).toContainText("overwrite: checkpoint-proof.txt")
  await dialog.getByRole("button", { name: "Confirm restore" }).click()
  await expect(dialog.getByText(/pinned recovery backup/)).toBeVisible()
  expect(readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("unstaged")
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staging-only preview proof")
  expect(readFileSync(join(cwd, "secret"), "utf8")).toBe("never captured")
})


test("production Pi refuses safe rename and arbitrary shell with unchanged sentinels and visible diagnostics", async ({ launchApp }) => {
  const { window, repoPath, home } = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-safe-refusals", authRoute: "api-key" } })
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByTestId("new-session").click()
  await expect(window.getByText(/File rename is unsupported in safe mode; no files are changed/)).toBeVisible()
  await window.getByLabel("Checkpoint-safe mode", { exact: true }).check()
  await window.getByRole("button", { name: "Create workspace" }).click()
  await expect(window.getByRole("button", { name: "More conversation actions" })).toBeVisible({ timeout: 20000 })
  const session = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))[0]
  const sentinels = { "rename-source.txt": "original source", "rename-destination.txt": "original destination", "shell-sentinel.txt": "original shell sentinel" }
  for (const [path, content] of Object.entries(sentinels)) writeFileSync(join(session.worktreePath, path), content)
  const composer = window.getByPlaceholder("Message the agent…")
  await composer.fill("Attempt checkpoint-safe rename and arbitrary shell"); await composer.press("Enter")
  const diagnostic = window.getByText(/^Safe refusal diagnostics:/)
  await expect(diagnostic).toContainText("Rename is unsupported in checkpoint-safe mode", { timeout: 20000 })
  await expect(diagnostic).toContainText("Shell/build/test")
  for (const [path, content] of Object.entries(sentinels)) expect(readFileSync(join(session.worktreePath, path), "utf8")).toBe(content)
  const transcript = () => readFileSync(join(home, "jingler/transcripts", `${encodeURIComponent(session.activeChatId)}.json`), "utf8")
  await expect.poll(transcript).toContain("workspace_rename")
  await expect.poll(transcript).toContain("command_execute")
  await expect.poll(transcript).toContain("Rename is unsupported in checkpoint-safe mode")
  await expect.poll(transcript).toContain("Shell/build/test")
})

test("conversation checkpoint dialog keeps its owner when the selected session changes", async ({ launchApp }) => {
  const { window, repoPath, home } = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-checkpoints", authRoute: "api-key" } })
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click()
  await addProject(window, repoPath)
  await window.keyboard.press("Escape")
  const sessions = (): Array<{ id: string; worktreePath: string }> => JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  for (let index = 0; index < 2; index++) {
    await window.getByTestId("new-session").click()
    await window.getByLabel("Checkpoint-safe mode", { exact: true }).check()
    await window.getByRole("button", { name: "Create workspace" }).click()
    await expect(window.getByRole("button", { name: "More conversation actions" })).toBeVisible({ timeout: 20000 })
    await expect.poll(() => sessions().length).toBe(index + 1)
  }
  const [owner, other] = sessions()
  expect(owner).toBeDefined()
  expect(other).toBeDefined()
  if (!owner || !other) throw new Error("Expected two managed workspaces")
  await window.getByTestId(`session-row-${owner.id}`).click()
  const trigger = window.getByRole("button", { name: "More conversation actions" })
  await expect(window.getByRole("button", { name: "Checkpoints", exact: true })).toHaveCount(0)
  await trigger.focus()
  await window.keyboard.press("ArrowDown")
  await expect(window.getByRole("menuitem", { name: "Checkpoints" })).toBeFocused()
  await window.keyboard.press("Enter")
  const dialog = window.getByRole("dialog", { name: "Workspace checkpoints" })
  await expect(dialog.getByRole("button", { name: "Capture checkpoint" })).toBeVisible()
  await expect.poll(() => dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
  // A modal blocks pointer navigation. Dispatch a real sidebar event to model
  // an independent navigation request arriving while its captured owner is open.
  await window.getByTestId(`session-row-${other.id}`).dispatchEvent("click")
  await expect(window.getByTestId(`session-row-${other.id}`)).toHaveClass(/border-blue/)
  await expect(dialog).toBeVisible()
  await dialog.getByRole("button", { name: "Capture checkpoint" }).click()
  await expect(dialog.getByRole("button", { name: "Cancel" })).toBeEnabled()
  const snapshots = () => readdirSync(join(home, "jingler/checkpoints")).flatMap((directory) =>
    readdirSync(join(home, "jingler/checkpoints", directory)).filter((id) => !id.endsWith(".tmp")).map((id) =>
      JSON.parse(readFileSync(join(home, "jingler/checkpoints", directory, id, "snapshot.json"), "utf8"))))
  await expect.poll(() => snapshots().filter((item) => item.summary.sessionId === owner.id && item.summary.label === "Manual checkpoint").length).toBe(1)
  expect(snapshots().filter((item) => item.summary.sessionId === other.id && item.summary.label === "Manual checkpoint")).toHaveLength(0)
  await dialog.getByRole("button", { name: "Disable safe mode" }).click()
  await expect(dialog.getByRole("button", { name: "Enable safe mode" })).toBeVisible()
  await dialog.getByRole("button", { name: "Enable safe mode" }).click()
  await expect(dialog.getByRole("button", { name: "Agree and enable" })).toBeVisible()
  await window.keyboard.press("Escape")
  await expect(dialog.getByRole("button", { name: "Enable safe mode" })).toBeVisible()
  await expect(dialog).toBeVisible()
  await window.keyboard.press("Escape")
  await expect(dialog).toHaveCount(0)
  await expect(window.getByRole("button", { name: "More conversation actions" })).toBeVisible()
})
