import { createHash } from "node:crypto"
import { existsSync, readFileSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { addProject, appShell, expect, test } from "./fixtures.js"

test("saves a routine through Settings and runs the real checkpoint-gated Pi into a linked fresh worktree", async ({ launchApp }) => {
  test.setTimeout(180000)
  const launched = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  const { window, repoPath, home } = launched
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Settings" }).click()
  await window.getByRole("button", { name: "Projects", exact: true }).click()
  const routines = window.getByRole("region", { name: "Saved desktop routines" })
  await routines.getByLabel("Name", { exact: true }).fill("Routine proof")
  await routines.getByLabel("Prompt", { exact: true }).fill("READONLY routine proof: inspect README.md")
  await expect(routines.getByText("Permissions: Ask. No automatic escalation.")).toBeVisible()
  await routines.getByText("Full routine safety details", { exact: true }).click()
  await expect(routines.getByText(/File rename is unsupported in safe mode; no files are changed/)).toBeVisible()
  await expect(routines.getByRole("checkbox", { name: /I approve these exact settings/ })).toHaveAttribute("aria-checked", "false")
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await expect(routines.getByRole("alert")).toContainText("Approve these exact settings")
  expect(existsSync(join(home, "jingler/routines.json")) ? JSON.parse(readFileSync(join(home, "jingler/routines.json"), "utf8")).routines : []).toEqual([])
  await routines.getByRole("checkbox", { name: /I approve these exact settings/ }).click()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  const document = () => JSON.parse(readFileSync(join(home, "jingler/routines.json"), "utf8"))
  await expect.poll(() => document().runs[0]?.status).toBe("running")
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  await expect.poll(() => document().runs.filter((run: { status: string }) => run.status === "skipped").length).toBe(1)
  await expect.poll(() => document().runs[0]?.status, { timeout: 30000 }).toBe("succeeded")
  const run = document().runs[0]
  const sessions = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  const session = sessions.find((item: { id: string }) => item.id === run.requestedSessionId)
  expect(run.sessionId).toBe(session.id)
  expect(session.routineOccurrence).toEqual({ routineId: run.routineId, runId: run.id })
  expect(session.modelId).toBe(document().routines[0].modelId)
  expect(session.connectionId).toBe(document().routines[0].connectionId)
  expect(session.endpointId).toBe(document().routines[0].endpointId)
  expect(session.checkpointSafeMode).toBe(true); expect(session.checkpointExecutionHistory).toBe("clean")
  expect(session.workspaceLifecycle.status).toBe("setup-skipped")
  expect(session.worktreePath).not.toBe(repoPath)
  expect(readFileSync(join(session.worktreePath, "README.md"), "utf8")).toBe("# e2e repo\n")
  expect(session.chats.find((chat: { id: string }) => chat.id === session.activeChatId).mode).toBe("ask")
  expect(readFileSync(join(repoPath, "README.md"), "utf8")).toBe("# e2e repo\n")
  expect(existsSync(join(repoPath, "routine-proof.txt"))).toBe(false)
  const checkpointRoot = join(home, "jingler/checkpoints", createHash("sha256").update(session.id).digest("hex"))
  const snapshots = readdirSync(checkpointRoot).filter(id => !id.endsWith(".tmp")).map(id => JSON.parse(readFileSync(join(checkpointRoot, id, "snapshot.json"), "utf8")))
  expect(snapshots.some(item => item.summary.label.startsWith("Before agent turn"))).toBe(true)
  const transcript = () => readFileSync(join(home, "jingler/transcripts", `${encodeURIComponent(session.activeChatId)}.json`), "utf8")
  await expect.poll(transcript).toContain("workspace_read_file")
  expect(transcript()).toContain("# e2e repo")
  await expect(routines.getByRole("button", { name: "Open workspace Routine proof" })).toBeVisible()
  await routines.getByRole("button", { name: "Edit Routine proof", exact: true }).click()
  await routines.getByRole("button", { name: "Schedule", exact: true }).click()
  await routines.getByRole("option", { name: "Fixed interval", exact: true }).click()
  const next = new Date(Date.now() + 5000)
  const local = new Date(next.getTime() - next.getTimezoneOffset() * 60000).toISOString().slice(0, 19)
  await routines.getByLabel("First occurrence").fill(local)
  await routines.getByLabel("Interval minutes").fill("1")
  await routines.getByRole("switch", { name: "Enable schedule" }).click()
  await routines.getByRole("checkbox", { name: /I approve these exact settings/ }).click()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await expect.poll(() => document().runs.filter((item: { trigger: string; status: string }) => item.trigger === "scheduled" && item.status === "succeeded").length, { timeout: 30000 }).toBe(1)
  const disabledDueAt = document().routines[0].nextAt as number
  expect(disabledDueAt).toBeGreaterThan(Date.now())
  await routines.getByRole("button", { name: "Edit Routine proof", exact: true }).click()
  await expect(routines.getByRole("switch", { name: "Enable schedule" })).toHaveAttribute("aria-checked", "true")
  await routines.getByRole("button", { name: "Disable Routine proof", exact: true }).click()
  await expect.poll(() => document().routines[0].enabled).toBe(false)
  await expect(routines.getByRole("switch", { name: "Enable schedule" })).toHaveAttribute("aria-checked", "false")
  await routines.getByRole("checkbox", { name: /I approve these exact settings/ }).click()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await expect(routines.getByRole("button", { name: "Enable Routine proof", exact: true })).toBeVisible()
  expect(document().routines[0].enabled).toBe(false)
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  await expect(routines.getByRole("button", { name: "Cancel Routine proof", exact: true })).toBeVisible()
  await routines.getByRole("button", { name: "Cancel Routine proof", exact: true }).click()
  await expect.poll(() => document().runs.filter((item: { status: string }) => item.status === "cancelled").length).toBe(1)

  await routines.getByRole("button", { name: "Open workspace Routine proof" }).first().click()
  await expect(window.getByRole("button", { name: "More conversation actions" })).toBeVisible()
  const ids = document().runs.map((item: { id: string }) => item.id)
  // Cross the actual persisted due time while disabled; checking only the flag
  // would miss a stale armed timer that still dispatches an occurrence.
  await expect.poll(() => {
    expect(document().runs.map((item: { id: string }) => item.id)).toEqual(ids)
    return Date.now()
  }, { timeout: 75000, intervals: [250] }).toBeGreaterThan(disabledDueAt + 1000)
  expect(document().routines[0].enabled).toBe(false)
  await launched.app.close()
  const reopened = await launchApp({ home, reposDir: launched.reposDir, userDataDir: launched.userDataDir, configured: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  await expect(appShell(reopened.window)).toBeVisible()
  await reopened.window.getByRole("button", { name: "Account menu" }).click()
  await reopened.window.getByRole("menuitem", { name: "Settings" }).click()
  await reopened.window.getByRole("button", { name: "Projects", exact: true }).click()
  await expect(reopened.window.getByRole("button", { name: "Run now Routine proof", exact: true })).toBeVisible()
  await expect(reopened.window.getByRole("button", { name: "Enable Routine proof", exact: true })).toBeVisible()
  const saved = reopened.window.getByRole("region", { name: "Saved desktop routines" })
  await expect(saved).toContainText("Routine proof: succeeded")
  await expect(saved).toContainText("Routine proof: cancelled")
  const restartSettledAt = Math.max(Date.now() + 2000, disabledDueAt + 6000)
  await expect.poll(() => {
    expect(document().routines[0].enabled).toBe(false)
    expect(document().runs.map((item: { id: string }) => item.id)).toEqual(ids)
    return Date.now()
  }, { intervals: [250] }).toBeGreaterThan(restartSettledAt)
  // Re-enabling a missed occurrence records a skip, never a catch-up workspace.
  const beforeEnable = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8")).map((item: { id: string }) => item.id)
  await saved.getByRole("button", { name: "Enable Routine proof", exact: true }).click()
  await expect.poll(() => document().runs.length).toBe(ids.length + 1)
  const missed = document().runs.find((item: { id: string }) => !ids.includes(item.id))
  expect(missed.status).toBe("skipped")
  expect(missed.message).toContain("no catch-up")
  expect(JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8")).map((item: { id: string }) => item.id)).toEqual(beforeEnable)
  await saved.getByRole("button", { name: "Disable Routine proof", exact: true }).click()
  await expect.poll(() => document().routines[0].enabled).toBe(false)
  const retainedIds = document().runs.map((item: { id: string }) => item.id)
  await saved.getByRole("button", { name: "Delete Routine proof", exact: true }).click()
  await expect.poll(() => document().routines.length).toBe(0)
  await expect(saved.getByRole("button", { name: "Run now Routine proof", exact: true })).toHaveCount(0)
  expect(document().runs.map((item: { id: string }) => item.id)).toEqual(retainedIds)
  await expect(saved).toContainText("Routine proof: succeeded")
  await reopened.app.close()
  const afterDelete = await launchApp({ home, reposDir: launched.reposDir, userDataDir: launched.userDataDir, configured: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  await expect(appShell(afterDelete.window)).toBeVisible()
  await afterDelete.window.getByRole("button", { name: "Account menu" }).click()
  await afterDelete.window.getByRole("menuitem", { name: "Settings" }).click()
  await afterDelete.window.getByRole("button", { name: "Projects", exact: true }).click()
  const deleted = afterDelete.window.getByRole("region", { name: "Saved desktop routines" })
  await expect(deleted.getByRole("button", { name: "Run now Routine proof", exact: true })).toHaveCount(0)
  await expect(deleted).toContainText("Routine proof: succeeded")
  await expect(deleted.getByRole("heading", { name: "All-project run history" })).toBeVisible()
  await expect(deleted.getByText("Deleted routine", { exact: true }).first()).toBeVisible()
  await expect(deleted.getByRole("button", { name: "Open workspace Routine proof" }).first()).toBeVisible()
  expect(document().routines).toEqual([])
  expect(document().runs.map((item: { id: string }) => item.id)).toEqual(retainedIds)
})

test("Ask WRITE routine needs attention without approval or mutation", async ({ launchApp }) => {
  const { window, repoPath, home } = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Settings" }).click()
  await window.getByRole("button", { name: "Projects", exact: true }).click()
  const routines = window.getByRole("region", { name: "Saved desktop routines" })
  await routines.getByLabel("Name", { exact: true }).fill("Ask write proof")
  await routines.getByLabel("Prompt", { exact: true }).fill("WRITE routine proof: write routine-proof.txt")
  await routines.getByRole("checkbox", { name: /I approve these exact settings/ }).click()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await routines.getByRole("button", { name: "Run now Ask write proof", exact: true }).click()
  const document = () => JSON.parse(readFileSync(join(home, "jingler/routines.json"), "utf8"))
  await expect.poll(() => document().runs[0]?.status, { timeout: 30000 }).toBe("needs-attention")
  const run = document().runs[0]
  const sessions = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  const session = sessions.find((item: { id: string }) => item.id === run.requestedSessionId)
  expect(session.chats.find((chat: { id: string }) => chat.id === session.activeChatId).mode).toBe("ask")
  expect(session.modelId).toBe(document().routines[0].modelId)
  expect(session.connectionId).toBe(document().routines[0].connectionId)
  expect(session.endpointId).toBe(document().routines[0].endpointId)
  expect(session.checkpointSafeMode).toBe(true)
  expect(existsSync(join(session.worktreePath, "routine-proof.txt"))).toBe(false)
  expect(existsSync(join(repoPath, "routine-proof.txt"))).toBe(false)
  expect(readFileSync(join(repoPath, "README.md"), "utf8")).toBe("# e2e repo\n")
})

test("signing out before a scheduled occurrence gates unattended and manual dispatch", async ({ launchApp }) => {
  const { window, repoPath, home } = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-routines", authRoute: "api-key" } })
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Settings" }).click()
  await window.getByRole("button", { name: "Projects", exact: true }).click()
  const routines = window.getByRole("region", { name: "Saved desktop routines" })
  await routines.getByLabel("Name", { exact: true }).fill("Auth gated proof")
  await routines.getByLabel("Prompt", { exact: true }).fill("READONLY routine proof: inspect README.md")
  const dueAt = Date.now() + 10000
  const local = new Date(dueAt - new Date(dueAt).getTimezoneOffset() * 60000).toISOString().slice(0, 19)
  await routines.getByLabel("First occurrence").fill(local)
  await routines.getByRole("switch", { name: "Enable schedule" }).click()
  await routines.getByRole("checkbox", { name: /I approve these exact settings/ }).click()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await expect(routines.getByRole("button", { name: "Disable Auth gated proof", exact: true })).toBeVisible()
  const document = () => JSON.parse(readFileSync(join(home, "jingler/routines.json"), "utf8"))
  const sessionIds = () => existsSync(join(home, "jingler/sessions.json")) ? JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8")).map((item: { id: string }) => item.id) : []
  const before = sessionIds()
  expect(document().runs).toEqual([])
  await window.getByRole("button", { name: "Close settings" }).click()
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Sign out", exact: true }).click()
  await expect(window.getByRole("button", { name: "Account menu" })).toContainText("Not signed in")
  // Prove signout completed before the occurrence rather than winning a timer race.
  expect(Date.now()).toBeLessThan(document().routines[0].nextAt)
  await expect.poll(() => {
    expect(document().runs).toEqual([])
    expect(sessionIds()).toEqual(before)
    return Date.now()
  }, { timeout: 15000, intervals: [250] }).toBeGreaterThan(dueAt + 1500)
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Settings" }).click()
  await window.getByRole("button", { name: "Projects", exact: true }).click()
  await routines.getByRole("button", { name: "Run now Auth gated proof", exact: true }).click()
  await expect(routines.getByRole("alert")).toContainText(/Sign in|signed out|suspended|unavailable/i)
  expect(document().runs).toEqual([])
  expect(sessionIds()).toEqual(before)
})
