import { execFileSync } from "node:child_process"
import { readFileSync, writeFileSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { addProject, appShell, expect, test } from "./fixtures.js"

test("safe creation captures before the production Pi turn and restores files and staging while preserving secrets", async ({ launchApp }) => {
  const { window, repoPath, home } = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-checkpoints", authRoute: "api-key" } })
  const git = (cwd: string, ...args: string[]) => execFileSync("git", args, { cwd, encoding: "utf8", stdio: "pipe" }).trim()
  writeFileSync(join(repoPath, "checkpoint-proof.txt"), "base")
  writeFileSync(join(repoPath, ".gitignore"), "secret\n")
  git(repoPath, "add", "."); git(repoPath, "commit", "-qm", "checkpoint fixture")
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByTestId("new-session").click()
  await window.getByLabel("Checkpoint-safe mode", { exact: true }).check()
  await window.getByRole("button", { name: "Create workspace" }).click()
  await expect(window.getByTestId("workspace-checkpoints")).toBeVisible({ timeout: 20000 })
  const sessions = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  const session = sessions[0] as { worktreePath: string; checkpointSafeMode: boolean; checkpointExecutionHistory: string }
  expect(session.checkpointSafeMode).toBe(true); expect(session.checkpointExecutionHistory).toBe("clean")
  const cwd = session.worktreePath
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "staged"); git(cwd, "add", "checkpoint-proof.txt")
  writeFileSync(join(cwd, "checkpoint-proof.txt"), "unstaged")
  writeFileSync(join(cwd, "secret"), "never captured")
  const composer = window.getByPlaceholder("Message the agent…")
  writeFileSync(join(cwd, "intent"), "untracked"); git(cwd, "add", "-N", "intent")
  await composer.fill("Edit the checkpoint proof"); await composer.press("Enter")
  await expect(window.getByText(/Checkpoint capture failed; the turn was blocked/)).toBeVisible({ timeout: 20000 })
  expect(readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("unstaged")
  await expect(window.getByText("Checkpoint edit complete.", { exact: true })).toHaveCount(0)
  git(cwd, "reset", "--", "intent")
  await composer.fill("Retry the checkpoint edit"); await composer.press("Enter")
  await expect.poll(() => readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("changed")
  await window.getByRole("button", { name: "Checkpoints", exact: true }).click()
  const activeDialog = window.getByRole("dialog", { name: "Workspace checkpoints" })
  await activeDialog.getByText(/Before agent turn/).locator("..").getByRole("button", { name: "Preview restore" }).click()
  await expect(activeDialog.getByRole("alert")).toContainText("Stop all workspace work")
  await expect(window.getByText("Checkpoint edit complete.", { exact: true })).toHaveCount(0)
  await activeDialog.getByRole("button", { name: "Cancel" }).click()
  await activeDialog.getByRole("button", { name: "Cancel" }).click()
  await expect(window.getByText("Checkpoint edit complete.", { exact: true })).toBeVisible({ timeout: 20000 })
  expect(readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("changed")
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staged")
  const root = join(home, "jingler/checkpoints")
  const snapshots = readdirSync(root).flatMap((owner) => readdirSync(join(root, owner)).filter((id) => !id.endsWith(".tmp")).map((id) => JSON.parse(readFileSync(join(root, owner, id, "snapshot.json"), "utf8"))))
  expect(snapshots.some((item) => item.summary.label.startsWith("Before agent turn"))).toBe(true)
  expect(snapshots.every((item) => !item.files.some((file: { path: string }) => file.path === "secret"))).toBe(true)
  await window.getByRole("button", { name: "Checkpoints", exact: true }).click()
  const dialog = window.getByRole("dialog", { name: "Workspace checkpoints" })
  await dialog.getByText(/Before agent turn/).locator("..").getByRole("button", { name: "Preview restore" }).click()
  await expect(dialog.getByText("overwrite: checkpoint-proof.txt", { exact: true })).toBeVisible()
  await expect(dialog).toContainText("Stop external editors and file watchers before confirming")
  await expect(dialog).toContainText("cannot lock external writers")
  await dialog.getByRole("button", { name: "Confirm restore" }).click()
  await expect(dialog.getByText(/pinned recovery backup/)).toBeVisible()
  expect(readFileSync(join(cwd, "checkpoint-proof.txt"), "utf8")).toBe("unstaged")
  expect(git(cwd, "show", ":checkpoint-proof.txt")).toBe("staged")
  expect(readFileSync(join(cwd, "secret"), "utf8")).toBe("never captured")
})
