import { existsSync, readFileSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { addProject, appShell, expect, test } from "./fixtures.js"

test("saves a routine through Settings and runs the real checkpoint-gated Pi into a linked fresh worktree", async ({ launchApp }) => {
  const launched = await launchApp({ configured: true, withRepo: true, piFixture: { scenarioId: "workspace-checkpoints", authRoute: "api-key" } })
  const { window, repoPath, home } = launched
  await expect(appShell(window)).toBeVisible()
  await window.getByTestId("new-session").click(); await addProject(window, repoPath); await window.keyboard.press("Escape")
  await window.getByRole("button", { name: "Account menu" }).click()
  await window.getByRole("menuitem", { name: "Settings" }).click()
  await window.getByRole("button", { name: "Routines", exact: true }).click()
  const routines = window.getByRole("region", { name: "Saved desktop routines" })
  await routines.getByLabel("Name", { exact: true }).fill("Routine proof")
  await routines.getByLabel("Prompt", { exact: true }).fill("Edit the checkpoint proof")
  await routines.getByLabel(/I approve these exact settings/).check()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  const document = () => JSON.parse(readFileSync(join(home, "jingler/routines.json"), "utf8"))
  await expect.poll(() => document().runs[0]?.status).toBe("running")
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  await expect.poll(() => document().runs.filter((run: { status: string }) => run.status === "skipped").length).toBe(1)
  await expect.poll(() => document().runs[0]?.status, { timeout: 30000 }).toBe("succeeded")
  const run = document().runs[0]
  const sessions = JSON.parse(readFileSync(join(home, "jingler/sessions.json"), "utf8"))
  const session = sessions.find((item: { id: string }) => item.id === run.requestedSessionId)
  expect(run.sessionId).toBe(session.id)
  expect(session.routineOccurrence).toEqual({ routineId: run.routineId, runId: run.id })
  expect(session.checkpointSafeMode).toBe(true); expect(session.checkpointExecutionHistory).toBe("clean")
  expect(session.workspaceLifecycle.status).toBe("setup-skipped")
  expect(session.worktreePath).not.toBe(repoPath)
  expect(readFileSync(join(session.worktreePath, "checkpoint-proof.txt"), "utf8")).toBe("changed")
  expect(existsSync(join(repoPath, "checkpoint-proof.txt"))).toBe(false)
  expect(readdirSync(join(home, "jingler/checkpoints")).flatMap(owner => readdirSync(join(home, "jingler/checkpoints", owner))).length).toBeGreaterThan(0)
  await expect(routines.getByRole("button", { name: "Open workspace Routine proof" })).toBeVisible()
  await routines.getByRole("button", { name: "Edit Routine proof", exact: true }).click()
  await routines.getByLabel("Schedule", { exact: true }).selectOption("interval")
  const next = new Date(Date.now() + 5000)
  const local = new Date(next.getTime() - next.getTimezoneOffset() * 60000).toISOString().slice(0, 19)
  await routines.getByLabel("First occurrence").fill(local)
  await routines.getByLabel("Interval minutes").fill("1")
  await routines.getByLabel("Enable schedule").check()
  await routines.getByLabel(/I approve these exact settings/).check()
  await routines.getByRole("button", { name: "Save routine", exact: true }).click()
  await expect.poll(() => document().runs.filter((item: { trigger: string; status: string }) => item.trigger === "scheduled" && item.status === "succeeded").length, { timeout: 30000 }).toBe(1)
  await routines.getByRole("button", { name: "Disable Routine proof", exact: true }).click()
  await expect.poll(() => document().routines[0].enabled).toBe(false)
  await routines.getByRole("button", { name: "Run now Routine proof", exact: true }).click()
  await expect(routines.getByRole("button", { name: "Cancel Routine proof", exact: true })).toBeVisible()
  await routines.getByRole("button", { name: "Cancel Routine proof", exact: true }).click()
  await expect.poll(() => document().runs.filter((item: { status: string }) => item.status === "cancelled").length).toBe(1)

  await routines.getByRole("button", { name: "Open workspace Routine proof" }).first().click()
  await expect(window.getByTestId("workspace-checkpoints")).toBeVisible()
  const ids = document().runs.map((item: { id: string }) => item.id)
  await launched.app.close()
  const reopened = await launchApp({ home, reposDir: launched.reposDir, userDataDir: launched.userDataDir, configured: true, piFixture: { scenarioId: "workspace-checkpoints", authRoute: "api-key" } })
  await expect(appShell(reopened.window)).toBeVisible()
  await reopened.window.getByRole("button", { name: "Account menu" }).click()
  await reopened.window.getByRole("menuitem", { name: "Settings" }).click()
  await reopened.window.getByRole("button", { name: "Routines", exact: true }).click()
  await expect(reopened.window.getByRole("button", { name: "Run now Routine proof", exact: true })).toBeVisible()
  expect(document().runs.map((item: { id: string }) => item.id)).toEqual(ids)

})
