import { type ReactNode, useState } from "react"
import { AnimatePresence, m } from "motion/react"
import { Check, ChevronDown, Copy, ImageIcon } from "lucide-react"
import { cn } from "../../lib/cn.js"
import { FAST, SPRING } from "../../lib/motion.js"
import { Loader } from "../../components/beui/feedback.js"

export function AgentCodeBlock({ code, language, filename, lineNumbers = false, focusedLines = [], streaming = false, className }: { code: string; language?: string; filename?: string; lineNumbers?: boolean; focusedLines?: ReadonlyArray<number>; streaming?: boolean; className?: string }) {
  const [copied, setCopied] = useState(false)
  const lines = code.split("\n")
  const copy = async () => { await navigator.clipboard?.writeText(code); setCopied(true); window.setTimeout(() => setCopied(false), 1400) }
  return <figure className={cn("overflow-hidden rounded-lg border border-line bg-sunken", className)}><figcaption className="flex h-8 items-center gap-2 border-b border-line px-3 font-mono text-[9.5px] text-dim"><span className="flex-1 truncate">{filename ?? language ?? "code"}</span>{streaming && <span className="flex items-center gap-1 text-blue"><Loader size={10} />streaming</span>}<button type="button" aria-label="Copy code" onClick={() => void copy()} className="rounded p-1 hover:bg-surface hover:text-text">{copied ? <Check className="size-3 text-green" /> : <Copy className="size-3" />}</button></figcaption><pre className="max-h-80 overflow-auto p-3 font-mono text-[11px] leading-[1.6] text-text-body"><code>{lines.map((line, index) => <span key={index} className={cn("block min-w-max", focusedLines.includes(index + 1) && "bg-selection")}><span className={cn("mr-3 inline-block w-6 select-none text-right text-dim", !lineNumbers && "hidden")}>{index + 1}</span>{line || " "}</span>)}</code></pre></figure>
}

export interface AgentDiffLine { type: "context" | "add" | "delete"; oldLine?: number; newLine?: number; content: string }
export function AgentFileDiff({ path, lines, added, removed, complete = true, defaultOpen = true, className }: { path: string; lines: ReadonlyArray<AgentDiffLine>; added?: number; removed?: number; complete?: boolean; defaultOpen?: boolean; className?: string }) {
  const [open, setOpen] = useState(defaultOpen)
  return <section className={cn("overflow-hidden rounded-lg border border-line bg-sunken", className)}><button type="button" aria-expanded={open} onClick={() => setOpen(value => !value)} className="flex w-full items-center gap-2 bg-panel px-3 py-2 text-left"><span className="min-w-0 flex-1 truncate font-mono text-[10.5px] text-text">{path}</span><span className="font-mono text-[9.5px] text-green">+{added ?? lines.filter(line => line.type === "add").length}</span><span className="font-mono text-[9.5px] text-red">−{removed ?? lines.filter(line => line.type === "delete").length}</span>{!complete && <Loader size={11} />}<ChevronDown className={cn("size-3.5 text-dim transition-transform", open && "rotate-180")} /></button><AnimatePresence initial={false}>{open && <m.div initial={{ height: 0 }} animate={{ height: "auto" }} exit={{ height: 0 }} transition={SPRING} className="overflow-hidden"><pre className="max-h-80 overflow-auto border-t border-line py-1 font-mono text-[10.5px] leading-[1.55]">{lines.map((line,index) => <div key={index} className={cn("flex min-w-max", line.type === "add" ? "bg-diff-add" : line.type === "delete" ? "bg-diff-del" : "text-muted-foreground")}><span className="w-10 select-none pr-2 text-right text-dim">{line.oldLine ?? ""}</span><span className="w-10 select-none pr-2 text-right text-dim">{line.newLine ?? ""}</span><span className={cn("w-4 select-none", line.type === "add" ? "text-green" : line.type === "delete" ? "text-red" : "text-dim")}>{line.type === "add" ? "+" : line.type === "delete" ? "−" : " "}</span><code className="pr-3 text-text-body">{line.content}</code></div>)}</pre></m.div>}</AnimatePresence></section>
}

export function ImageGeneration({ src, alt, status = "complete", progress, prompt, actions, className }: { src?: string; alt: string; status?: "queued" | "generating" | "complete" | "error"; progress?: number; prompt?: ReactNode; actions?: ReactNode; className?: string }) {
  return <figure className={cn("overflow-hidden rounded-xl border border-line bg-sunken", className)}><div className="relative aspect-video overflow-hidden">{src ? <m.img src={src} alt={alt} initial={{ opacity: 0, filter: "blur(12px)" }} animate={{ opacity: status === "queued" ? .25 : 1, filter: status === "complete" ? "blur(0px)" : "blur(4px)" }} transition={{ duration: .4 }} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-dim"><ImageIcon className="size-8" /></div>}{status !== "complete" && <div className="absolute inset-0 flex items-center justify-center bg-overlay/40"><div role="status" className="rounded-lg border border-line bg-panel/90 px-3 py-2 text-[11px] text-text"><span className="flex items-center gap-2"><Loader size={12} />{status === "queued" ? "Queued" : status === "error" ? "Generation failed" : `Generating${progress === undefined ? "…" : ` ${Math.round(progress)}%`}`}</span></div></div>}</div>{(prompt || actions) && <figcaption className="flex items-center gap-2 border-t border-line px-3 py-2 text-[10.5px] text-muted-foreground"><span className="min-w-0 flex-1 truncate">{prompt}</span>{actions}</figcaption>}</figure>
}
