import { type ReactNode, useState } from "react"
import { AnimatePresence, m } from "motion/react"
import { Check, ChevronDown, Circle, CircleStop, LoaderCircle, Send, ShieldCheck, X } from "lucide-react"
import { cn } from "../../lib/cn.js"
import { FAST, SPRING } from "../../lib/motion.js"
import { Loader } from "../../components/beui/feedback.js"
import { Button } from "../../components/button.js"

export function PromptInputSurface({ children, className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div data-slot="prompt-input" className={cn("rounded-xl border border-line bg-panel shadow-[0_8px_30px_-20px_var(--sb-shadow-strong)] transition-[border-color,box-shadow] focus-within:border-brand/45 focus-within:shadow-[0_10px_36px_-18px_var(--sb-shadow-strong)]", className)} {...props}>{children}</div>
}

export function PromptInput({ value, onValueChange, onSubmit, onStop, busy = false, placeholder = "Message the agent…", actions, model, footer, disabled, className }: { value: string; onValueChange?: (value: string) => void; onSubmit?: () => void; onStop?: () => void; busy?: boolean; placeholder?: string; actions?: ReactNode; model?: ReactNode; footer?: ReactNode; disabled?: boolean; className?: string }) {
  const send = () => { if (!disabled && value.trim()) onSubmit?.() }
  return <PromptInputSurface className={cn("p-2", className)}><textarea value={value} onChange={event => onValueChange?.(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send() } }} disabled={disabled} placeholder={placeholder} rows={1} className="field-sizing-content max-h-44 min-h-12 w-full resize-none bg-transparent px-2 py-1 text-[13px] leading-relaxed text-text outline-none placeholder:text-dim" /><div className="flex items-center gap-1.5">{actions}<div className="flex-1" />{model}<m.button type="button" whileTap={{ scale: .92 }} transition={SPRING} disabled={!busy && (!value.trim() || disabled)} onClick={busy ? onStop : send} aria-label={busy ? "Stop response" : "Send message"} className={cn("flex size-8 items-center justify-center rounded-lg outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-35", busy ? "bg-red/15 text-red" : "bg-brand text-white hover:bg-brand-hover")}>{busy ? <CircleStop className="size-4" /> : <Send className="size-4" />}</m.button></div>{footer && <div className="mt-2 border-t border-line px-1 pt-2">{footer}</div>}</PromptInputSurface>
}

export type AgentTodoStatus = "pending" | "running" | "done" | "blocked"
export interface AgentTodoItem { id: string; title: ReactNode; status: AgentTodoStatus; meta?: ReactNode }
export function AgentTodoList({ items, title = "Tasks", defaultOpen = true, className }: { items: ReadonlyArray<AgentTodoItem>; title?: ReactNode; defaultOpen?: boolean; className?: string }) {
  const [open, setOpen] = useState(defaultOpen)
  const done = items.filter(item => item.status === "done").length
  const icon = (status: AgentTodoStatus) => status === "done" ? <Check className="size-3.5 text-green" /> : status === "running" ? <LoaderCircle className="size-3.5 animate-spin text-blue" /> : status === "blocked" ? <X className="size-3.5 text-red" /> : <Circle className="size-3.5 text-dim" />
  return <section className={cn("overflow-hidden rounded-xl border border-line bg-panel", className)}><button type="button" aria-expanded={open} onClick={() => setOpen(value => !value)} className="flex w-full items-center gap-2 px-3 py-2.5 text-left"><strong className="flex-1 text-[12px] text-text-bright">{title}</strong><span className="font-mono text-[10px] text-dim">{done}/{items.length}</span><m.span animate={{ rotate: open ? 180 : 0 }} transition={SPRING}><ChevronDown className="size-3.5 text-dim" /></m.span></button><AnimatePresence initial={false}>{open && <m.div initial={{ height: 0 }} animate={{ height: "auto" }} exit={{ height: 0 }} transition={SPRING} className="overflow-hidden"><ol className="border-t border-line p-1.5">{items.map(item => <m.li layout key={item.id} className="flex items-center gap-2 rounded-md px-2 py-1.5 text-[12px] text-text">{icon(item.status)}<span className={cn("min-w-0 flex-1", item.status === "done" && "text-muted-foreground line-through")}>{item.title}</span>{item.meta && <span className="font-mono text-[9px] text-dim">{item.meta}</span>}</m.li>)}</ol></m.div>}</AnimatePresence></section>
}

export interface AgentActivityItem { id: string; label: ReactNode; detail?: ReactNode; status?: "running" | "success" | "error" | "idle"; icon?: ReactNode; timestamp?: ReactNode }
export function AgentActivity({ items, label = "Agent activity", className }: { items: ReadonlyArray<AgentActivityItem>; label?: string; className?: string }) {
  return <ol aria-label={label} className={cn("relative flex flex-col gap-1 before:absolute before:bottom-3 before:left-[13px] before:top-3 before:w-px before:bg-line", className)}>{items.map(item => <m.li layout key={item.id} className="relative flex gap-2 rounded-lg px-1.5 py-2 hover:bg-surface"><span className={cn("z-10 flex size-4 flex-none items-center justify-center rounded-full bg-panel", item.status === "success" ? "text-green" : item.status === "error" ? "text-red" : item.status === "running" ? "text-blue" : "text-dim")}>{item.icon ?? (item.status === "running" ? <Loader size={12} /> : item.status === "success" ? <Check className="size-3" /> : <Circle className="size-2.5" />)}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-[11px] text-text"><span className="flex-1">{item.label}</span>{item.timestamp && <span className="font-mono text-[9px] text-dim">{item.timestamp}</span>}</div>{item.detail && <div className="mt-1 text-[10.5px] text-muted-foreground">{item.detail}</div>}</div></m.li>)}</ol>
}

export function AgentLoadingState({ label = "Thinking", detail, progress, phrases, className }: { label?: string; detail?: ReactNode; progress?: number; phrases?: ReadonlyArray<string>; className?: string }) {
  const [index, setIndex] = useState(0)
  const phrase = phrases?.[index % phrases.length]
  return <div role="status" className={cn("flex items-center gap-2.5 rounded-lg border border-line bg-panel px-3 py-2.5", className)}><Loader variant="dots" size={13} /><div className="min-w-0 flex-1"><div className="text-[11px] text-text"><span className="bg-[linear-gradient(100deg,var(--sb-muted),var(--sb-text-bright),var(--sb-muted))] bg-[length:220%_100%] bg-clip-text text-transparent animate-shine">{phrase ?? label}</span></div>{detail && <div className="mt-0.5 text-[10px] text-dim">{detail}</div>}{progress !== undefined && <div className="mt-1.5 h-0.5 overflow-hidden rounded-full bg-line"><m.div animate={{ width: `${Math.max(0, Math.min(100, progress))}%` }} transition={SPRING} className="h-full bg-brand" /></div>}</div>{phrases && phrases.length > 1 && <button type="button" aria-label="Next status" onClick={() => setIndex(value => value + 1)} className="sr-only">Next</button>}</div>
}

export function ToolResultSurface({ children, className, ...props }: React.HTMLAttributes<HTMLElement>) {
  return <section data-slot="tool-result" className={cn("overflow-hidden rounded-lg border border-line bg-panel", className)} {...props}>{children}</section>
}

export function ToolResult({ title, status = "success", summary, children, defaultOpen = false, onStop, className }: { title: ReactNode; status?: "running" | "success" | "error"; summary?: ReactNode; children?: ReactNode; defaultOpen?: boolean; onStop?: () => void; className?: string }) {
  const [open, setOpen] = useState(defaultOpen)
  return <ToolResultSurface className={cn(status === "running" ? "border-yellow/35 bg-yellow/[0.04]" : status === "error" ? "border-red/35 bg-red/[0.04]" : undefined, className)}><div className="flex"><button type="button" aria-expanded={open} disabled={!children} onClick={() => setOpen(value => !value)} className="flex min-w-0 flex-1 items-center gap-2 px-3 py-2 text-left text-[11px]"><span className={status === "success" ? "text-green" : status === "error" ? "text-red" : "text-yellow"}>{status === "running" ? <Loader size={12} /> : status === "success" ? <Check className="size-3.5" /> : <X className="size-3.5" />}</span><strong className="text-text">{title}</strong><span className="min-w-0 flex-1 truncate text-muted-foreground">{summary}</span>{children && <ChevronDown className={cn("size-3 text-dim transition-transform", open && "rotate-180")} />}</button>{status === "running" && onStop && <button type="button" aria-label="Stop tool" onClick={onStop} className="px-3 text-red hover:bg-red/10"><CircleStop className="size-3.5" /></button>}</div><AnimatePresence initial={false}>{open && children && <m.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={SPRING} className="overflow-hidden border-t border-line"><div className="max-h-72 overflow-auto bg-sunken p-3 font-mono text-[10.5px] text-muted-foreground">{children}</div></m.div>}</AnimatePresence></ToolResultSurface>
}

export function ApprovalCard({ title, description, choices, value, onValueChange, custom, onCustomChange, onSubmit, submitLabel = "Continue", className }: { title: ReactNode; description?: ReactNode; choices?: ReadonlyArray<{ value: string; label: ReactNode; description?: ReactNode }>; value?: string; onValueChange?: (value: string) => void; custom?: string; onCustomChange?: (value: string) => void; onSubmit?: () => void; submitLabel?: string; className?: string }) {
  return <section className={cn("rounded-xl border border-blue/35 bg-blue/[0.05] p-3", className)}><div className="mb-3"><strong className="text-[12px] text-text-bright">{title}</strong>{description && <p className="mt-1 text-[11px] text-muted-foreground">{description}</p>}</div>{choices && <div role="radiogroup" className="mb-3 grid gap-1.5">{choices.map(choice => <button key={choice.value} type="button" role="radio" aria-checked={value === choice.value} onClick={() => onValueChange?.(choice.value)} className={cn("rounded-lg border px-3 py-2 text-left", value === choice.value ? "border-blue/50 bg-blue/10" : "border-line bg-panel hover:bg-surface")}><span className="text-[11px] text-text">{choice.label}</span>{choice.description && <span className="mt-0.5 block text-[10px] text-dim">{choice.description}</span>}</button>)}</div>}{custom !== undefined && <textarea value={custom} onChange={event => onCustomChange?.(event.target.value)} className="mb-3 min-h-16 w-full rounded-lg border border-line bg-sunken p-2 text-[11px] text-text outline-none focus:ring-2 focus:ring-ring" />}<div className="flex justify-end"><Button size="sm" onClick={onSubmit}>{submitLabel}</Button></div></section>
}

export function ToolApprovalSurface({ children, className, ...props }: React.HTMLAttributes<HTMLElement>) {
  return <section data-slot="tool-approval" className={cn("overflow-hidden rounded-xl border border-blue/45 bg-blue/[0.05]", className)} {...props}>{children}</section>
}

export function ToolApproval({ title, detail, command, status = "pending", rememberLabel, onDecision, className }: { title: ReactNode; detail?: ReactNode; command?: ReactNode; status?: "pending" | "allowed" | "denied"; rememberLabel?: ReactNode; onDecision?: (decision: "deny" | "allow" | "always") => void; className?: string }) {
  return <ToolApprovalSurface className={cn(status === "allowed" ? "border-green/35 bg-green/[0.04]" : status === "denied" ? "border-red/35 bg-red/[0.04]" : undefined, className)}><header className="flex items-center gap-2 border-b border-line/70 px-3 py-2.5"><ShieldCheck className={cn("size-4", status === "pending" ? "text-blue" : status === "allowed" ? "text-green" : "text-red")} /><strong className="flex-1 text-[12px] text-text-bright">{title}</strong><span className="font-mono text-[9px] uppercase text-dim">{status}</span></header><div className="p-3">{command && <div className="mb-2 overflow-auto rounded-md border border-line bg-sunken p-2 font-mono text-[10.5px] text-text">{command}</div>}{detail && <p className="text-[11px] text-muted-foreground">{detail}</p>}{status === "pending" && <div className="mt-3 flex items-center gap-2"><Button variant="danger" size="sm" onClick={() => onDecision?.("deny")}>Deny</Button><div className="flex-1" />{rememberLabel && <Button variant="secondary" size="sm" onClick={() => onDecision?.("always")}>{rememberLabel}</Button>}<Button size="sm" onClick={() => onDecision?.("allow")}>Allow once</Button></div>}</div></ToolApprovalSurface>
}
