// Foundation
export * from "./hooks/use-container-width.js"
export * from "./hooks/width-tier.js"
export * from "./lib/cn.js"
export * from "./lib/review-feedback.js"
export * from "./lib/reasoning-options.js"
export * from "./lib/connector-labels.js"
export * from "./lib/relative-time.js"
export * from "./tokens.js"

// Atoms / primitives (shadcn base)
export * from "./components/status-dot.js"
export * from "./components/signal-bars.js"
export * from "./components/kbd.js"
export * from "./components/badge.js"
export * from "./components/pill.js"
export * from "./components/button.js"
export * from "./components/button-group.js"
export * from "./components/async-button.js"
export * from "./components/feedback.js"
export * from "./components/avatar.js"
export * from "./components/toggle.js"
export * from "./components/loading.js"
export * from "./components/eyebrow.js"
export * from "./components/diff-stat.js"
export * from "./components/segmented-control.js"
export * from "./components/filter-menu.js"
export * from "./components/resizable.js"
export * from "./components/search-input.js"
export * from "./components/callout.js"
export * from "./components/card.js"
export * from "./components/dialog.js"
export * from "./components/command.js"
export * from "./components/input.js"
export * from "./components/select.js"
export * from "./components/file-icon.js"
export * from "./components/diff-peek.js"
export * from "./components/html-preview.js"
export * from "./components/code-chip.js"
export * from "./components/markdown.js"
export * from "./components/chip-menu.js"
export * from "./components/context-menu.js"
export * from "./components/hover-card.js"
export * from "./components/confirm-dialog.js"
export * from "./components/provider-icon.js"
export * from "./components/connector-logo.js"
export * from "./components/oauth-button.js"
export * from "./components/auth-divider.js"
export * from "./components/starfield.js"

// Molecules / composites
export * from "./composites/tool-call.js"
export * from "./composites/thought-block.js"
export * from "./composites/phase-node.js"
export * from "./composites/agent-card.js"
export * from "./composites/background-task-dock.js"
export * from "./composites/approval-gate.js"
export * from "./composites/slash-command-row.js"
export * from "./composites/connector-center.js"
export * from "./composites/connector-detail.js"
export * from "./composites/connectors-settings.js"
export * from "./composites/injection-targets.js"
export * from "./composites/open-connector-section.js"
export * from "./composites/pr-glyph.js"
export * from "./composites/session-row.js"
export * from "./composites/session-hover-card.js"
export * from "./composites/composer.js"
export * from "./composites/message-turn.js"
export * from "./composites/run-stats.js"
export * from "./composites/queued-message-row.js"
export * from "./composites/context-meter.js"
export * from "./composites/context-divider.js"
export * from "./composites/mode-switch.js"
export * from "./composites/command-menu.js"
export * from "./composites/mention-menu.js"
export * from "./composites/new-session-dialog.js"
export * from "./composites/pr-picker-list.js"
export * from "./composites/issue-picker-list.js"
export * from "./composites/archived-banner.js"
export * from "./composites/usage-modal.js"
export * from "./composites/question-card.js"
export * from "./composites/question-summary.js"
export * from "./composites/settings-dialog.js"
export * from "./composites/settings-view.js"
export * from "./composites/provider-card.js"
export * from "./composites/pull-request-view.js"
export * from "./composites/pr-timeline-entry.js"
export * from "./composites/pr-review-thread.js"
export * from "./composites/pr-review-group.js"
export * from "./composites/pr-review-composer.js"
export * from "./composites/pr-side-panel.js"
export * from "./composites/review-findings.js"
export * from "./composites/pr-check-row.js"
export * from "./composites/code-review-view.js"
export * from "./composites/review-file-row.js"
export * from "./composites/review-diff.js"
export * from "./composites/inline-comment-composer.js"
export * from "./composites/review-tray.js"
export * from "./composites/plan-card.js"
export * from "./composites/plan-approval-actions.js"
export * from "./composites/plan-assignee.js"
export * from "./composites/plan-step-list.js"
export * from "./composites/plan-challenges.js"
export * from "./composites/plan-flow.js"
export * from "./composites/plan-step-detail.js"
export * from "./composites/auth-card.js"
export * from "./composites/magic-link-form.js"
export * from "./composites/user-menu.js"

// Diff engine (virtualized)
export * from "./diff/parse.js"
export * from "./diff/highlight.js"
export * from "./diff/use-highlight.js"
export * from "./diff/diff-view.js"
export * from "./diff/diff-hunk.js"
export * from "./diff/parse-diff-hunk.js"
export * from "./diff/review-thread-hunk.js"

// Asset viewer (Preview dock)
export * from "./asset/csv-parse.js"
export * from "./asset/csv-table.js"
export * from "./asset/asset-view.js"
export * from "./asset/path-detect.js"
export * from "./asset/open-asset-context.js"

// App compositions
export * from "./app/title-bar.js"
export * from "./app/tab-bar.js"
export * from "./app/tab-contributions.js"
// `./app/keybinding-contributions.js` is deliberately NOT exported.
//
// The module and its tests are complete, but nothing dispatches
// `matchKeybinding` and the loader refuses any manifest declaring
// `contributes.keybindings` (see `plugin-loader.ts`). Publishing the resolver
// from this index would commit the package to an API for a feature the app
// currently declines to ship — a surface future readers must understand and
// keep compiling, with no caller to justify either. `pane-contributions` earned
// its export by being wired in; this one has not yet.
//
// Add the export back in the same change that removes `contributes.keybindings`
// from the loader's `unsupported` list and hooks the dispatch up.
export * from "./app/pane-contributions.js"
export * from "./app/command-palette.js"
export * from "./app/command-palette-model.js"
export * from "./app/agent-tab-bar.js"
export * from "./app/subagent-view.js"
export * from "./app/session-filters.js"
export * from "./app/session-sidebar.js"
export * from "./app/conversation-view.js"
export * from "./app/diff-panel.js"
export * from "./app/terminal-panel.js"
export * from "./app/preview-dock.js"
export * from "./app/app-shell.js"
export * from "./app/starbase-app.js"

// Screens
export * from "./screens/session-conversation.js"
export * from "./screens/plan-review.js"
export * from "./screens/empty-conversation.js"
export * from "./screens/component-library.js"
export * from "./screens/stub-screen.js"
export * from "./screens/setup-screen.js"
export * from "./screens/loading-screen.js"
export * from "./screens/login-screen.js"

// Seed data
export * from "./seed.js"
export * from "./theme-provider.js"
export * from "./composites/themes-settings.js"
export * from "./composites/plugins-settings.js"
