/**
 * `starbase-plugin://` — how a plugin's ES module reaches the renderer.
 *
 * ## Why a custom scheme at all
 *
 * The renderer's CSP is `script-src 'self'`, and it must stay close to that:
 * the one thing an agent harness must never do is execute code it fetched over
 * the network. But plugin UI is, unavoidably, code the renderer has to import.
 *
 * A custom scheme squares that circle. It is registered as **standard** (so URLs
 * parse with an origin and ES module resolution works against it) and **secure**
 * (so it counts as a trustworthy origin and is not downgraded like `file:`),
 * and the handler below only ever answers with bytes from inside
 * `~/starbase/plugins`. CSP then widens by exactly one source —
 * `script-src 'self' starbase-plugin:` — and every other directive is untouched.
 * `connect-src` in particular stays closed, so a plugin's UI half cannot reach
 * the network even though it can now be loaded from disk.
 *
 * ## The two things this file guards
 *
 * 1. **Traversal.** A plugin id and a path both arrive from the renderer, which
 *    is running third-party code by the time this matters. Every resolved path
 *    is re-checked against the plugins root AFTER `realpath`, so a symlink
 *    inside a plugin directory pointing at `~/.ssh` is refused just as firmly as
 *    a literal `../../`.
 * 2. **Module identity.** Two plugins importing `react` must get the SAME React,
 *    or hooks throw and nothing renders. The `runtime` host serves generated
 *    shims that re-export the app's already-instantiated singletons rather than
 *    a second copy of the library — see {@link RUNTIME_MODULES}.
 */
import { readFile, realpath, stat } from "node:fs/promises"
import { extname, join, resolve, sep } from "node:path"
import { protocol } from "electron"
// Imported for their EXPORT NAMES only — the shims re-export off the renderer's
// instances at runtime, never off these. Main and the renderer each load their
// own copy of React; that is fine precisely because nothing here is ever called.
import * as React from "react"
import * as JsxRuntime from "react/jsx-runtime"
import * as ReactDom from "react-dom"
import * as JsxDevRuntime from "react/jsx-dev-runtime"
import * as Sdk from "@starbase/plugin-sdk"
// NOT `import * as SdkUi from "@starbase/plugin-sdk/ui"`. That would make the
// MAIN process load the whole component library — shiki, katex, a graph layout
// engine — at startup, to serve a few hundred bytes of re-exports. The names
// come from a data module that imports nothing; a test in the SDK asserts the
// two agree.
import { UI_EXPORT_NAMES } from "@starbase/plugin-sdk/ui-exports"
import { builtinPluginsRoot, pluginsRoot } from "./app-paths.js"

/** The scheme, in one place — it appears in CSP, in the importmap and here. */
export const PLUGIN_SCHEME = "starbase-plugin"

/**
 * The reserved host that serves runtime shims rather than plugin files.
 *
 * A plugin can never be called this: {@link PLUGIN_SCHEME} URLs put the plugin
 * id in the host position, and `PluginId` in `@starbase/core` forbids nothing
 * about the word "runtime" — so this module refuses it explicitly at install
 * time instead of letting a plugin shadow React.
 */
export const RUNTIME_HOST = "runtime"

/**
 * Every re-exportable binding of a module namespace.
 *
 * DERIVED, never hand-listed. An ES module's export list has to be static, so
 * the shims below spell out each binding — and a hardcoded list would silently
 * fall behind the moment someone added a hook to the SDK, handing plugins
 * `undefined` for an export that plainly exists. Reading the real namespace
 * means the shim cannot drift from what it is shimming.
 *
 * Filtered to valid identifiers: a namespace carries `default` (re-exported
 * separately below) and may carry `__esModule` or `Symbol.toStringTag`, none of
 * which are legal in an `export const` position.
 */
const exportNames = (namespace: object): ReadonlyArray<string> =>
  Object.keys(namespace)
    .filter((name) => name !== "default" && name !== "__esModule")
    .filter((name) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name))
    .sort()

/**
 * Build one shim module: pull the singleton off the global, re-export by name.
 *
 * The thrown error is not decoration. Without it a plugin imported before the
 * runtime is published gets `undefined` for every binding, and fails several
 * frames later inside its own component with nothing naming Starbase.
 */
const runtimeShim = (globalKey: string, names: ReadonlyArray<string>): string => `\
// Generated by plugin-protocol.ts from the live module — do not edit.
const runtime = globalThis.__STARBASE_RUNTIME__
if (!runtime) {
  throw new Error(
    "Starbase plugin runtime is not published yet. A plugin module was imported before the app finished booting."
  )
}
const mod = runtime.${globalKey}
${names.map((n) => `export const ${n} = mod.${n}`).join("\n")}
export default mod
`

/**
 * The modules a plugin may import as bare specifiers.
 *
 * Each is a tiny generated ES module re-exporting off the object the renderer
 * publishes before React mounts (`renderer/plugin-runtime.ts`). Serving the real
 * library instead would give every plugin its own React instance, and two
 * Reacts in one tree makes every hook throw — but only once a SECOND plugin is
 * installed, so it is a bug an author ships having genuinely tested.
 *
 * The same reasoning applies to the SDK, and more sharply: the SDK owns the
 * React context the plugin hooks read, and a context object is only meaningful
 * to the module instance that created it. A plugin holding a second copy of the
 * SDK would call `useHost()` inside a plugin view and be told it was outside one.
 */
const RUNTIME_MODULES: Record<string, string> = {
  "react.js": runtimeShim("react", exportNames(React)),
  "jsx-runtime.js": runtimeShim("jsxRuntime", exportNames(JsxRuntime)),
  // Its OWN shim. Aliasing this to react.js served a module exporting none of
  // `createPortal`, `createRoot` or `flushSync`, so any plugin importing one
  // failed to instantiate.
  "react-dom.js": runtimeShim("reactDom", exportNames(ReactDom)),
  // React only ships `jsx-dev-runtime` in development builds; falling back to
  // the production namespace keeps a plugin built in dev mode loadable against
  // a packaged app, where `jsxDEV` does not exist.
  "jsx-dev-runtime.js": runtimeShim(
    "jsxRuntime",
    exportNames({ ...JsxRuntime, ...JsxDevRuntime })
  ),
  "sdk.js": runtimeShim("sdk", exportNames(Sdk)),
  "sdk-ui.js": runtimeShim("sdkUi", [...UI_EXPORT_NAMES])
}

/**
 * Bare specifiers a plugin may import, and the shim each resolves to.
 *
 * ## Why these are rewritten rather than left to the importmap
 *
 * `index.html` declares an import map covering exactly these, and in a browser
 * that is the whole mechanism. It is not sufficient here. The packaged renderer
 * is loaded with `loadFile`, so the document's origin is `file:` while a plugin
 * module's origin is `starbase-plugin:` — and in that arrangement Chromium does
 * not apply the document's import map to the plugin module's own imports. The
 * plugin fails with "Failed to resolve module specifier", having never reached
 * a line of its own code.
 *
 * Found by the e2e spec, which is the only test that runs a real renderer
 * against a real custom-scheme module. Nothing smaller would have caught it.
 *
 * So the handler rewrites them on the way out. The import map stays as well —
 * it costs nothing, and it keeps `import` maps working for anything loaded from
 * the document's own origin — but correctness no longer depends on it.
 */
const BARE_SPECIFIERS: Record<string, string> = {
  react: `${PLUGIN_SCHEME}://${RUNTIME_HOST}/react.js`,
  "react-dom": `${PLUGIN_SCHEME}://${RUNTIME_HOST}/react-dom.js`,
  "react/jsx-runtime": `${PLUGIN_SCHEME}://${RUNTIME_HOST}/jsx-runtime.js`,
  "react/jsx-dev-runtime": `${PLUGIN_SCHEME}://${RUNTIME_HOST}/jsx-dev-runtime.js`,
  "@starbase/plugin-sdk": `${PLUGIN_SCHEME}://${RUNTIME_HOST}/sdk.js`,
  "@starbase/plugin-sdk/ui": `${PLUGIN_SCHEME}://${RUNTIME_HOST}/sdk-ui.js`
}

/**
 * Point a module's bare specifiers at their shims.
 *
 * Deliberately narrow. It only rewrites a quoted specifier that follows `from`
 * or a bare `import`/`export`, and only when the specifier is EXACTLY one of the
 * six above — so an unrelated string that merely contains the word `react` is
 * untouched, and a specifier the app does not provide is left alone to fail
 * loudly rather than being silently redirected somewhere plausible.
 *
 * A full parse would be more correct and is not worth it: these are ES modules
 * emitted by a bundler, where every import is a top-level static statement.
 */
const rewriteSpecifiers = (source: string): string =>
  source.replace(
    /(\bfrom\s*|\bimport\s*|\bexport\s*\*\s*from\s*)(["'])([^"']+)\2/g,
    (match, prefix: string, quote: string, specifier: string) => {
      const target = BARE_SPECIFIERS[specifier]
      return target ? `${prefix}${quote}${target}${quote}` : match
    }
  )

/** Rewriting only makes sense for JavaScript. */
const isModule = (file: string): boolean => /\.m?js$/i.test(file)

const MIME: Record<string, string> = {
  ".js": "text/javascript",
  ".mjs": "text/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".map": "application/json"
}

const mimeFor = (file: string): string =>
  MIME[extname(file).toLowerCase()] ?? "application/octet-stream"

const notFound = () => new Response("Not found", { status: 404 })

/**
 * Register the scheme's privileges.
 *
 * MUST run at module scope, before `app.whenReady()` — Electron reads this
 * table when the protocol subsystem starts, and a call afterwards is silently
 * ignored, which presents as a plugin whose module 404s for no visible reason.
 *
 * - `standard` gives the scheme an origin, which ES module resolution and
 *   relative `import "./x.js"` inside a plugin both require.
 * - `secure` keeps it out of the mixed-content downgrade path.
 * - `supportFetchAPI` lets a plugin `fetch()` its own bundled assets.
 * - `stream` matters for anything large enough to be worth not buffering.
 */
export const registerPluginScheme = (): void => {
  protocol.registerSchemesAsPrivileged([
    {
      scheme: PLUGIN_SCHEME,
      privileges: {
        standard: true,
        secure: true,
        supportFetchAPI: true,
        stream: true,
        corsEnabled: true
      }
    }
  ])
}

/**
 * Resolve a request path to a real file inside a plugin's directory, or null.
 *
 * Null covers every refusal — traversal, a missing plugin, a directory, a
 * symlink escaping the root — deliberately: a 404 tells a caller only "not
 * here", whereas distinguishing "refused" from "absent" would let a plugin map
 * the operator's filesystem one probe at a time.
 */
export const resolvePluginAsset = async (
  pluginId: string,
  requestPath: string
): Promise<string | null> => {
  if (!pluginId || pluginId === RUNTIME_HOST) return null
  // Reject the id before it ever touches the filesystem. `PluginId` in
  // `@starbase/core` already constrains this, but the renderer is not the only
  // possible caller of a URL and this is the cheaper of the two checks.
  if (!/^[a-z0-9][a-z0-9-]*$/.test(pluginId)) return null

  const relative = decodeURIComponent(requestPath).replace(/^\/+/, "")
  if (!relative) return null

  // BOTH roots. Official plugins are read from the app bundle rather than
  // copied into `~/starbase/plugins`, so a handler that knew only the installed
  // root served every bundled plugin a 404 — which presents as an official
  // plugin that appears in Settings and then fails to load, with the module
  // plainly present on disk.
  for (const rootPath of [pluginsRoot(), builtinPluginsRoot()]) {
    const root = resolve(rootPath)
    const pluginDir = resolve(root, pluginId)
    if (pluginDir !== join(root, pluginId)) continue

    const target = resolve(pluginDir, relative)
    // The lexical check catches `../..`; it does NOT catch a symlink, which is
    // why the realpath check below is not redundant.
    if (target !== pluginDir && !target.startsWith(pluginDir + sep)) continue

    try {
      const real = await realpath(target)
      // A plugin directory is third-party content. A symlink inside it pointing
      // at `~/.ssh/id_rsa` would otherwise be served happily by the lexical
      // check above, because the *link path* is innocent.
      const realRoot = await realpath(pluginDir)
      if (real !== realRoot && !real.startsWith(realRoot + sep)) continue
      const info = await stat(real)
      if (!info.isFile()) continue
      return real
    } catch {
      // Not under this root, or not readable. Try the next.
    }
  }
  return null
}

/**
 * Serve one request. Exported so the tests can exercise it without Electron.
 */
export const handlePluginRequest = async (url: string): Promise<Response> => {
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    return notFound()
  }

  if (parsed.hostname === RUNTIME_HOST) {
    const name = parsed.pathname.replace(/^\/+/, "")
    const source = RUNTIME_MODULES[name]
    if (!source) return notFound()
    return new Response(source, {
      status: 200,
      headers: {
        "content-type": "text/javascript",
        // Shims are generated per launch and never change within one; letting
        // the renderer cache them keeps a ten-plugin window to one fetch each.
        "cache-control": "no-cache"
      }
    })
  }

  const file = await resolvePluginAsset(parsed.hostname, parsed.pathname)
  if (!file) return notFound()

  try {
    const body = await readFile(file)
    const payload = isModule(file)
      ? new TextEncoder().encode(rewriteSpecifiers(body.toString("utf8")))
      : new Uint8Array(body)
    return new Response(payload, {
      status: 200,
      headers: {
        "content-type": mimeFor(file),
        // Plugins hot-reload on save; a cached module would mean an author edits
        // a file, sees nothing change, and concludes the watcher is broken.
        "cache-control": "no-store"
      }
    })
  } catch {
    return notFound()
  }
}

/**
 * Install the handler. Call after `app.whenReady()`.
 *
 * The handler buffers rather than streams. That is the right trade for modules
 * measured in kilobytes, and it also means a file being rewritten by an author's
 * editor is either served whole or not at all — a stream opened mid-save can
 * deliver a truncated module, which fails as a syntax error pointing at a line
 * the author never wrote.
 */
export const registerPluginProtocolHandler = (): void => {
  protocol.handle(PLUGIN_SCHEME, (request) => handlePluginRequest(request.url))
}
