/**
 * `starbase-plugin://` — how a plugin's ES module reaches the renderer.
 *
 * ## Why a custom scheme at all
 *
 * The renderer's CSP is `script-src 'self'`, and it must stay close to that:
 * the one thing an agent harness must never do is execute code it fetched over
 * the network. But plugin UI is, unavoidably, code the renderer has to import.
 *
 * A custom scheme squares that circle. It is registered as **standard** (so URLs
 * parse with an origin and ES module resolution works against it) and **secure**
 * (so it counts as a trustworthy origin and is not downgraded like `file:`),
 * and the handler below only ever answers with bytes from inside
 * `~/starbase/plugins`. CSP then widens by exactly one source —
 * `script-src 'self' starbase-plugin:` — and every other directive is untouched.
 * `connect-src` in particular stays closed, so a plugin's UI half cannot reach
 * the network even though it can now be loaded from disk.
 *
 * ## The two things this file guards
 *
 * 1. **Traversal.** A plugin id and a path both arrive from the renderer, which
 *    is running third-party code by the time this matters. Every resolved path
 *    is re-checked against the plugins root AFTER `realpath`, so a symlink
 *    inside a plugin directory pointing at `~/.ssh` is refused just as firmly as
 *    a literal `../../`.
 * 2. **Module identity.** Two plugins importing `react` must get the SAME React,
 *    or hooks throw and nothing renders. The `runtime` host serves generated
 *    shims that re-export the app's already-instantiated singletons rather than
 *    a second copy of the library — see {@link RUNTIME_MODULES}.
 */
import { readFile, realpath, stat } from "node:fs/promises"
import { extname, join, resolve, sep } from "node:path"
import { protocol } from "electron"
import { pluginsRoot } from "./app-paths.js"

/** The scheme, in one place — it appears in CSP, in the importmap and here. */
export const PLUGIN_SCHEME = "starbase-plugin"

/**
 * The reserved host that serves runtime shims rather than plugin files.
 *
 * A plugin can never be called this: {@link PLUGIN_SCHEME} URLs put the plugin
 * id in the host position, and `PluginId` in `@starbase/core` forbids nothing
 * about the word "runtime" — so this module refuses it explicitly at install
 * time instead of letting a plugin shadow React.
 */
export const RUNTIME_HOST = "runtime"

/**
 * The modules a plugin may import as bare specifiers.
 *
 * Each is a tiny generated ES module that re-exports off a global the renderer
 * publishes before React mounts (`plugin-runtime.ts`). Serving the real library
 * here instead would give every plugin its own React instance — two copies of
 * React in one tree means `useState` throws "invalid hook call", which surfaces
 * as a plugin that works alone and breaks the moment a second one is installed.
 *
 * The named re-exports are spelled out rather than star-exported because
 * `export * from` cannot re-export off a runtime object; the binding list has to
 * be static for an ES module.
 */
const RUNTIME_MODULES: Record<string, string> = {
  "react.js": runtimeShim("react", [
    "useState",
    "useEffect",
    "useMemo",
    "useCallback",
    "useRef",
    "useContext",
    "useReducer",
    "useLayoutEffect",
    "useSyncExternalStore",
    "useId",
    "useTransition",
    "createElement",
    "createContext",
    "forwardRef",
    "memo",
    "Fragment",
    "Suspense",
    "Component",
    "isValidElement",
    "cloneElement",
    "startTransition"
  ]),
  "jsx-runtime.js": runtimeShim("jsxRuntime", ["jsx", "jsxs", "Fragment"]),
  "jsx-dev-runtime.js": runtimeShim("jsxRuntime", ["jsxDEV", "jsx", "jsxs", "Fragment"]),
  "sdk.js": runtimeShim("sdk", [
    "useHost",
    "useSession",
    "usePluginStorage",
    "useCommand",
    "definePlugin",
    "defineManifest"
  ])
}

/** Build one shim module: pull the singleton off the global, re-export by name. */
function runtimeShim(globalKey: string, names: ReadonlyArray<string>): string {
  const bindings = names
    .map((n) => `export const ${n} = mod.${n}`)
    .join("\n")
  return `// Generated by plugin-protocol.ts — do not edit.
const runtime = globalThis.__STARBASE_RUNTIME__
if (!runtime) {
  throw new Error(
    "Starbase plugin runtime is not published yet. A plugin module was imported before the app finished booting."
  )
}
const mod = runtime.${globalKey}
${bindings}
export default mod
`
}

const MIME: Record<string, string> = {
  ".js": "text/javascript",
  ".mjs": "text/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".map": "application/json"
}

const mimeFor = (file: string): string =>
  MIME[extname(file).toLowerCase()] ?? "application/octet-stream"

const notFound = () => new Response("Not found", { status: 404 })

/**
 * Register the scheme's privileges.
 *
 * MUST run at module scope, before `app.whenReady()` — Electron reads this
 * table when the protocol subsystem starts, and a call afterwards is silently
 * ignored, which presents as a plugin whose module 404s for no visible reason.
 *
 * - `standard` gives the scheme an origin, which ES module resolution and
 *   relative `import "./x.js"` inside a plugin both require.
 * - `secure` keeps it out of the mixed-content downgrade path.
 * - `supportFetchAPI` lets a plugin `fetch()` its own bundled assets.
 * - `stream` matters for anything large enough to be worth not buffering.
 */
export const registerPluginScheme = (): void => {
  protocol.registerSchemesAsPrivileged([
    {
      scheme: PLUGIN_SCHEME,
      privileges: {
        standard: true,
        secure: true,
        supportFetchAPI: true,
        stream: true,
        corsEnabled: true
      }
    }
  ])
}

/**
 * Resolve a request path to a real file inside a plugin's directory, or null.
 *
 * Null covers every refusal — traversal, a missing plugin, a directory, a
 * symlink escaping the root — deliberately: a 404 tells a caller only "not
 * here", whereas distinguishing "refused" from "absent" would let a plugin map
 * the operator's filesystem one probe at a time.
 */
export const resolvePluginAsset = async (
  pluginId: string,
  requestPath: string
): Promise<string | null> => {
  if (!pluginId || pluginId === RUNTIME_HOST) return null
  // Reject the id before it ever touches the filesystem. `PluginId` in
  // `@starbase/core` already constrains this, but the renderer is not the only
  // possible caller of a URL and this is the cheaper of the two checks.
  if (!/^[a-z0-9][a-z0-9-]*$/.test(pluginId)) return null

  const root = resolve(pluginsRoot())
  const pluginDir = resolve(root, pluginId)
  if (pluginDir !== join(root, pluginId)) return null

  const relative = decodeURIComponent(requestPath).replace(/^\/+/, "")
  if (!relative) return null

  const target = resolve(pluginDir, relative)
  // The lexical check catches `../..`; it does NOT catch a symlink, which is
  // why the realpath check below is not redundant.
  if (target !== pluginDir && !target.startsWith(pluginDir + sep)) return null

  try {
    const real = await realpath(target)
    // A plugin directory is third-party content. A symlink inside it pointing at
    // `~/.ssh/id_rsa` would otherwise be served happily by the lexical check
    // above, because the *link path* is innocent.
    const realRoot = await realpath(pluginDir)
    if (real !== realRoot && !real.startsWith(realRoot + sep)) return null
    const info = await stat(real)
    if (!info.isFile()) return null
    return real
  } catch {
    return null
  }
}

/**
 * Serve one request. Exported so the tests can exercise it without Electron.
 */
export const handlePluginRequest = async (url: string): Promise<Response> => {
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    return notFound()
  }

  if (parsed.hostname === RUNTIME_HOST) {
    const name = parsed.pathname.replace(/^\/+/, "")
    const source = RUNTIME_MODULES[name]
    if (!source) return notFound()
    return new Response(source, {
      status: 200,
      headers: {
        "content-type": "text/javascript",
        // Shims are generated per launch and never change within one; letting
        // the renderer cache them keeps a ten-plugin window to one fetch each.
        "cache-control": "no-cache"
      }
    })
  }

  const file = await resolvePluginAsset(parsed.hostname, parsed.pathname)
  if (!file) return notFound()

  try {
    const body = await readFile(file)
    return new Response(new Uint8Array(body), {
      status: 200,
      headers: {
        "content-type": mimeFor(file),
        // Plugins hot-reload on save; a cached module would mean an author edits
        // a file, sees nothing change, and concludes the watcher is broken.
        "cache-control": "no-store"
      }
    })
  } catch {
    return notFound()
  }
}

/**
 * Install the handler. Call after `app.whenReady()`.
 *
 * The handler buffers rather than streams. That is the right trade for modules
 * measured in kilobytes, and it also means a file being rewritten by an author's
 * editor is either served whole or not at all — a stream opened mid-save can
 * deliver a truncated module, which fails as a syntax error pointing at a line
 * the author never wrote.
 */
export const registerPluginProtocolHandler = (): void => {
  protocol.handle(PLUGIN_SCHEME, (request) => handlePluginRequest(request.url))
}
